In [285]:
from sql_engine import connect
import pandas as pd

In [286]:
pd.set_option('display.float_format', lambda x: '%s' % x)

In [287]:
bi_con = connect('bidata')

In [315]:
df1 = pd.read_excel('易敏+方媛-卓越店长参会名单.xls',sheet_name='第一场参会名单1215')

In [316]:
# df1 = pd.read_excel('易敏+方媛-卓越店长参会名单.xls',sheet_name='第二场参会名单1248')

In [317]:
df1

,参会人姓名,电话,参会人身份,上级身份,上级姓名,所属总代,所属官方,所属联盟,区域经理,会场,支付状态,身份证号,地区,是否A+店主,是否5A店主,是否打款9600,其他人
0,陈普娟,13992468954.0,省代,总代,吴婷,吴婷,柏灵灵,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
1,宋宁,13061568735.0,总代,总代,宋宁,徐艳,杨慧,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
2,龙文,13135620882.0,总代,总代,龙文,杨慧,杨慧,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
3,赵紫娟,18609265202.0,省代,总代,孙福鑫,任晶,柏灵灵,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
4,黄柔君,13428334518.0,总代,总代,黄柔君,龙文,杨慧,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,王丽,15092285135.0,NaN,NaN,NaN,刘忠琴,杨大,传美黑马军团,崔颖,B1,NaN,NaN,nan,nan,nan,nan,nan
1211,陈亚群,18090841785.0,NaN,NaN,NaN,邓清艳,冉淋,传美黑马军团,崔颖,B1,NaN,NaN,nan,nan,nan,nan,nan
1212,单丹丹,13092575773.0,NaN,NaN,NaN,NaN,孙晓梅,传美黑马军团,黄桂芬,B1,NaN,NaN,nan,nan,nan,nan,nan
1213,李威,18626407777.0,NaN,NaN,NaN,NaN,孙晓梅,传美黑马军团,黄桂芬,B1,NaN,NaN,nan,nan,nan,nan,nan
1214,邱小玉,15271761490.0,NaN,NaN,NaN,NaN,孙晓梅,传美黑马军团,黄桂芬,B1,NaN,NaN,nan,nan,nan,nan,nan

In [324]:
df1.rename(columns={'电话':'userphone'},inplace=True)

In [325]:
df1

,参会人姓名,userphone,参会人身份,上级身份,上级姓名,所属总代,所属官方,所属联盟,区域经理,会场,支付状态,身份证号,地区,是否A+店主,是否5A店主,是否打款9600,其他人
0,陈普娟,13992468954.0,省代,总代,吴婷,吴婷,柏灵灵,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
1,宋宁,13061568735.0,总代,总代,宋宁,徐艳,杨慧,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
2,龙文,13135620882.0,总代,总代,龙文,杨慧,杨慧,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
3,赵紫娟,18609265202.0,省代,总代,孙福鑫,任晶,柏灵灵,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
4,黄柔君,13428334518.0,总代,总代,黄柔君,龙文,杨慧,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,王丽,15092285135.0,NaN,NaN,NaN,刘忠琴,杨大,传美黑马军团,崔颖,B1,NaN,NaN,nan,nan,nan,nan,nan
1211,陈亚群,18090841785.0,NaN,NaN,NaN,邓清艳,冉淋,传美黑马军团,崔颖,B1,NaN,NaN,nan,nan,nan,nan,nan
1212,单丹丹,13092575773.0,NaN,NaN,NaN,NaN,孙晓梅,传美黑马军团,黄桂芬,B1,NaN,NaN,nan,nan,nan,nan,nan
1213,李威,18626407777.0,NaN,NaN,NaN,NaN,孙晓梅,传美黑马军团,黄桂芬,B1,NaN,NaN,nan,nan,nan,nan,nan
1214,邱小玉,15271761490.0,NaN,NaN,NaN,NaN,孙晓梅,传美黑马军团,黄桂芬,B1,NaN,NaN,nan,nan,nan,nan,nan

In [326]:
df1['userphone'] = df1['userphone'].astype('str')

In [327]:
df1['userphone'][0]

'13992468954.0'

In [328]:
df1['userphone'] = df1['userphone'].apply(lambda x :x[:-2])

In [329]:
df1

,参会人姓名,userphone,参会人身份,上级身份,上级姓名,所属总代,所属官方,所属联盟,区域经理,会场,支付状态,身份证号,地区,是否A+店主,是否5A店主,是否打款9600,其他人
0,陈普娟,13992468954,省代,总代,吴婷,吴婷,柏灵灵,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
1,宋宁,13061568735,总代,总代,宋宁,徐艳,杨慧,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
2,龙文,13135620882,总代,总代,龙文,杨慧,杨慧,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
3,赵紫娟,18609265202,省代,总代,孙福鑫,任晶,柏灵灵,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
4,黄柔君,13428334518,总代,总代,黄柔君,龙文,杨慧,王者,李佳文,B1,已支付,NaN,nan,nan,nan,nan,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1210,王丽,15092285135,NaN,NaN,NaN,刘忠琴,杨大,传美黑马军团,崔颖,B1,NaN,NaN,nan,nan,nan,nan,nan
1211,陈亚群,18090841785,NaN,NaN,NaN,邓清艳,冉淋,传美黑马军团,崔颖,B1,NaN,NaN,nan,nan,nan,nan,nan
1212,单丹丹,13092575773,NaN,NaN,NaN,NaN,孙晓梅,传美黑马军团,黄桂芬,B1,NaN,NaN,nan,nan,nan,nan,nan
1213,李威,18626407777,NaN,NaN,NaN,NaN,孙晓梅,传美黑马军团,黄桂芬,B1,NaN,NaN,nan,nan,nan,nan,nan
1214,邱小玉,15271761490,NaN,NaN,NaN,NaN,孙晓梅,传美黑马军团,黄桂芬,B1,NaN,NaN,nan,nan,nan,nan,nan

In [330]:
df1 = df1[['参会人姓名','userphone']]

In [331]:
df1[df1['userphone'] == '18755863310']

Empty DataFrame
Columns: [参会人姓名, userphone]
Index: []

In [332]:
df1[df1['参会人姓名'] == '赵敏杰']

Empty DataFrame
Columns: [参会人姓名, userphone]
Index: []

In [333]:
df1.loc[:1214]

     参会人姓名    userphone
0      陈普娟  13992468954
1       宋宁  13061568735
2       龙文  13135620882
3      赵紫娟  18609265202
4      黄柔君  13428334518
...    ...          ...
1210    王丽  15092285135
1211   陈亚群  18090841785
1212   单丹丹  13092575773
1213    李威  18626407777
1214   邱小玉  15271761490

[1215 rows x 2 columns]

In [334]:
df2 = pd.read_sql('select * from InterMediate_agent_fullinfo',bi_con)

In [335]:
df2 = df2[['客户手机号','客户联合ID','客户姓名','客户等级','所属总代手机号','所属总代等级','所属总代姓名','所属官方','alliancename','省']]

In [336]:
df2.rename(columns={'客户手机号':'userphone'},inplace=True)

In [337]:
df2['userphone'] = df2['userphone'].astype('str')

In [338]:
df2[df2['userphone'] == '18755863310']

,userphone,客户联合ID,客户姓名,客户等级,所属总代手机号,所属总代等级,所属总代姓名,所属官方,alliancename,省
57820,18755863310,CM00003363,赵敏杰,2,18755863310,2.0,赵敏杰,徐丽芳,BOSS,河北省

In [339]:
df = pd.merge(df1,df2,how='left',left_on='userphone',right_on='userphone')

In [340]:
df

,参会人姓名,userphone,客户联合ID,客户姓名,客户等级,所属总代手机号,所属总代等级,所属总代姓名,所属官方,alliancename,省
0,陈普娟,13992468954,CM73768455,陈普娟,3.0,13001776346,2.0,吴婷,柏灵灵,王者,山东省
1,宋宁,13061568735,CM00003394,宋宁,2.0,13061568735,2.0,宋宁,杨慧,王者,山东省
2,龙文,13135620882,CM00000327,龙文,2.0,13135620882,2.0,龙文,杨慧,王者,湖北省
3,赵紫娟,18609265202,,赵紫娟,3.0,13384661128,1.0,柏灵灵,柏灵灵,王者,江苏省
4,黄柔君,13428334518,CM00000092,黄柔君,2.0,13428334518,2.0,黄柔君,杨慧,王者,广东省
...,...,...,...,...,...,...,...,...,...,...,...
1210,王丽,15092285135,CM35796413,王丽,5.0,15922168534,2.0,刘忠琴,杨大,黑马,山东省
1211,陈亚群,18090841785,,陈亚群,4.0,18281116168,2.0,邓清艳,冉淋,黑马,四川省
1212,单丹丹,13092575773,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,NaN
1213,李威,18626407777,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,NaN
1214,邱小玉,15271761490,NaN,NaN,nan,NaN,nan,NaN,NaN,NaN,NaN

In [341]:
df_count = df.groupby(['所属总代手机号','所属总代姓名'])['userphone'].count()

In [342]:
df_count.to_excel('aa.xlsx')

In [343]:
df[df['参会人姓名'] == '赵敏杰']

Empty DataFrame
Columns: [参会人姓名, userphone, 客户联合ID, 客户姓名, 客户等级, 所属总代手机号, 所属总代等级, 所属总代姓名, 所属官方, alliancename, 省]
Index: []

In [344]:
df.to_excel('bb.xlsx')